### ISSUE TITLE
用面向数据的思想实现3D旋转轮播图 :revolving_hearts:

### ISSUE THREAD

**Issue by liuyib** [liuyib/liuyib.github.io#1]
实现效果如下:

![slider_show](https://user-images.githubusercontent.com/38221479/51421257-d743b200-1bd6-11e9-8f8a-78992a952346.gif)

当然开始之前，你需要先准备几张图片，这里建议5张。
因为这个效果的实现原理是以数据为基础的，我这里只有五个可以拿来即用的数据。
如果图片超出五张的话，你需要自己手动写一下需要的数据。

---

基础的DOM结构如下:

```html
<div class="slider_wrapper" id="slider-wrapper">
  <div class="slider_imgs" id="slider-imgs">
    <ul>
      <li><img src="./imgs/1.png" alt="slider_img" /></li>
      <li><img src="./imgs/2.png" alt="slider_img" /></li>
      <li><img src="./imgs/3.png" alt="slider_img" /></li>
      <li><img src="./imgs/4.png" alt="slider_img" /></li>
      <li><img src="./imgs/5.png" alt="slider_img" /></li>
    </ul>

    <div class="slider_arrow" id="slider-arrow">
      <span id="slider-arrow-left">&lt;</span>
      <span id="slider-arrow-right">&gt;</span>
    </div>
  </div>
</div>
```

样式如下:

```css
div, span,
ul, li, img {
  margin: 0;
  padding: 0;
}
body {
  overflow: hidden;
  background: #666;
  padding: 50px;
}
li {
  list-style: none;
}

.slider_wrapper {
  width: 1200px;
  margin: 0 auto;
  margin-top: 60px;
}
.slider_imgs {
  position: relative;
  height: 430px;
  margin: 0 auto;
}
.slider_imgs li {
  position: absolute;
}
.slider_imgs img {
  width: 100%;
}

.slider_arrow {
  z-index: 999;
  position: relative;
  top: 50%;
  opacity: 0;
  -webkit-user-select: none;
  -moz-user-select: none;
  user-select: none;
  transition: opacity .3s ease;
}
.slider_wrapper:hover .slider_arrow {
  opacity: .5;
}
#slider-arrow-left,
#slider-arrow-right {
  z-index: 999;
  display: block;
  position: absolute;
  width: 50px;
  height: 50px;
  line-height: 40px;
  border-radius: 6px;
  text-align: center;
  font-size: 50px;
  font-weight: 600;
  background: #a9a9a9;
  color: #333;
  transform: translate(0, -50%);
  cursor: pointer;
}
#slider-arrow-right {
  right: 0;
}
```

样式和DOM结构不多BB，主要的心思放在效果实现上。这里我用了一个封装好的运动函数: `startMove`，代码如下:

```javascript
/**
 * 获取某个属性的值
 * @param {Object} elem 当前元素
 * @param {String} attr 属性
 */
function getStyle(elem, attr) {
  if (window.getComputedStyle) {
    return window.getComputedStyle(elem, null)[attr];
  } else {
    return elem.currentStyle[attr];
  }
}

/**
 * 运动函数
 * @param {Object}   elem 当前元素
 * @param {Object}   json 要操作的属性 // 传透明度属性时，范围是0-100
 * @param {Function} fn   回调函数
 * @param {Number}   slow 动画的缓慢程度 // 数值越大，动画越迟缓。
 * @param {Number}   time 每次动画执行时间
 */
function startMove(elem, json, fn = null, slow = 10, time = 15) {
  clearInterval(elem.timer);

  elem.timer = setInterval(function() {
    var bStop = true;
    
    for (var attr in json) {
      var iCur = 0;
      var target = json[attr];

      if (attr === "opacity") {
        iCur = getStyle(elem, attr) * 100 || 1;
      } else {
        iCur = parseInt(getStyle(elem, attr)) || 0;
      }

      var iSpeed = (target - iCur) / slow;
      iSpeed = iSpeed > 0 ? Math.ceil(iSpeed) : Math.floor(iSpeed);
      iCur += iSpeed;

      if (attr === "opacity") {
        elem.style.filter = "alpha(opacity=" + iCur + ")";
        elem.style[attr] = iCur / 100;
      } else if (attr === 'zIndex') {
        elem.style.zIndex = target;
      } else {
        elem.style[attr] = iCur + "px";
      }

      (iCur != target) && (bStop = false);
    }

    if (bStop) {
      clearInterval(elem.timer);
      fn && fn();
    }
  }, time);
}
```

这个函数实现的是缓冲运动，可以同时操作多个CSS属性，实现一些比较复杂的动画。

举个栗子:

利用上面的 `startMove` 实现下面这个效果：

![startmove_test1](https://user-images.githubusercontent.com/38221479/51421263-e296dd80-1bd6-11e9-9724-58cff209f4d6.gif)

代码如下：
```javascript
var oTest = document.getElementById('oTest');

startMove(oTest, {
  width: 100,
  height: 100,
  borderRadius: 100
}, function() {
  startMove(oTest, {
    width: 400,
    opacity: 60
  }, function() {
    startMove(oTest, {
      left: 200,
      top: 100,
      width: 100
    }, function() {
      startMove(oTest, {
        left: 150,
        top: 50,
        width: 200,
        height: 200
      }, function() {
        startMove(oTest, {
          left: 200,
          top: 100,
          width: 100,
          height: 100
        });
      });
    });
  });
}, 60, 20);
```

当然，上面这个效果比较复杂，所以代码有点臃肿。这也是 `startMove` 函数的一个缺点。

回到正题，现在来看一下3Ｄ轮播的效果是怎么实现的：

首先准备五个数据（文章开始提到的，当然你可以自己随意调整），这五个数据分别对应着图片显示的大小，位置，透明度 和 层级关系。

```javascript
var IMG_DATAS = [
  {
    width: 300,
    top: -20,
    left: 150,
    opacity: 20,
    zIndex: 2,
  },
  {
    width: 500,
    top: 30,
    left: 50,
    opacity: 80,
    zIndex: 3,
  },
  {
    width: 600,
    top: 100,
    left: 300,
    opacity: 100,
    zIndex: 4,
  },
  {
    width: 500,
    top: 30,
    left: 650,
    opacity: 80,
    zIndex: 3,
  },
  {
    width: 300,
    top: -20,
    left: 750,
    opacity: 20,
    zIndex: 2,
  }
];
```

然后我们将这五个数据和五张图片分别传入 `startMove`：

```javascript
var oImgsWrapper = document.getElementById('slider-imgs');
var aImgs = oImgsWrapper.getElementsByTagName('li');

function _startMove() {
  IMG_DATAS.forEach((item, index) => {
    startMove(aImgs[index], item, null);
  });
}

// init
_startMove();
```

这样，初始加载页面时，图片就会 `自动去找自己的位置`:

![slider_init](https://user-images.githubusercontent.com/38221479/51421266-edea0900-1bd6-11e9-9ccd-e73f7c5782fa.gif)

Cool！这就是 `面向数据编程` 的优点，我们只关心数据，通过数据来操控页面。数据的变化反应到页面上就实现了页面上的交互，动画，数据处理等等。目前很多前端流行的框架，都是这样。

这里我们想一下，既然初始的动画这个简单就完成了，那么切换的动画呢？！你可以先思考一下切换动画的实现（注意用 `面向数据的思想` 来思考）。

---

这里揭晓一下答案：

既然是面向数据，我们就只关心数据，剩下的动画部分交给 `startMove` 处理就好了。

图片左右切换，实际也就是那五个数据的切换。我们只需模拟队列，改变数据即可：`当点击左移时，将第一个数据从数组中移除，然后把这个数据添加到数组最后，最后将处理后的数组传给 startMove，这样，数据的流动反应到页面上就是图片的移动，很酷，不是吗？`

图片右移和左移同理。

核心代码如下：

```javascript
// 图片左移
IMG_DATAS.push(IMG_DATAS.shift());

// 图片右移
IMG_DATAS.unshift(IMG_DATAS.pop());
```

每次移动完以后，将处理后的数组传给 `startMove`:

```javascript
function _startMove() {
  IMG_DATAS.forEach((item, index) => {
    startMove(aImgs[index], item, null);
  });
}

_startMove();
```

完整代码如下：

```javascript
window.onload = function () {
  // Img datas
  var IMG_DATAS = [
    {
      width: 300,
      top: -20,
      left: 150,
      opacity: 20,
      zIndex: 2,
    },
    {
      width: 500,
      top: 30,
      left: 50,
      opacity: 80,
      zIndex: 3,
    },
    {
      width: 600,
      top: 100,
      left: 300,
      opacity: 100,
      zIndex: 4,
    },
    {
      width: 500,
      top: 30,
      left: 650,
      opacity: 80,
      zIndex: 3,
    },
    {
      width: 300,
      top: -20,
      left: 750,
      opacity: 20,
      zIndex: 2,
    }
  ];

  var oBtnLeft = document.getElementById('slider-arrow-left');
  var oBtnRight = document.getElementById('slider-arrow-right');
  var oImgsWrapper = document.getElementById('slider-imgs');
  var aImgs = oImgsWrapper.getElementsByTagName('li');

  function _startMove() {
    IMG_DATAS.forEach((item, index) => {
      startMove(aImgs[index], item, null);
    });
  }

  // init
  _startMove();

  oBtnLeft.onclick = function () {
    IMG_DATAS.push(IMG_DATAS.shift());
    _startMove();
  };

  oBtnRight.onclick = function () {
    IMG_DATAS.unshift(IMG_DATAS.pop());    
    _startMove();
  };
};
```

以上 :rocket:
